----------------------------------------
Timestamp: 2016/12/3 21:45:43

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:45:45

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:45:45

Title:用户 'sa' 登录失败。

Message: INSERT INTO [File] ([Id],[Domain],[FileName],[StoredFileName],[Length],[UploadDate],[UploadIPAddress]) VALUES(@Id,@Domain,@FileName,@StoredFileName,@Length,@UploadDate,@UploadIPAddress)
@Id:13297e19-ab42-49c1-b164-d0bfddcfb1c6 , @Domain:2a58d820-de07-4c8f-80b9-b5cb5a1028b4 , @FileName:QQGroup.JPG , @StoredFileName:6eb04f20-e1ad-41b4-bf19-ecf6e09102d5.JPG , @Length:98 , @UploadDate:2016/12/3 21:45:45 , @UploadIPAddress:::1 , 
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Linkup.Data.DatabaseWrapper.ExcuteSqlExpression(SqlExpression sqlExpression) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 310

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:45:45

Title:用户 'sa' 登录失败。

Message: SELECT * FROM [FileDownloadQueue] WHERE [Status] = @status ORDER BY [CreateTime] ASC
[{"ParameterName":"@status","Value":0}]
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetNewOpenConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetWrappedConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.LoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteDataSet(DbCommand command)
   在 Linkup.Data.DatabaseWrapper.ExecuteDataSet(CommandType commandType, String commandText, List`1 parameterList, String[] tableNameArray) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 264

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:45:50

Title:用户 'sa' 登录失败。

Message: INSERT INTO [File] ([Id],[Domain],[FileName],[StoredFileName],[Length],[UploadDate],[UploadIPAddress]) VALUES(@Id,@Domain,@FileName,@StoredFileName,@Length,@UploadDate,@UploadIPAddress)
@Id:13297e19-ab42-49c1-b164-d0bfddcfb1c6 , @Domain:2a58d820-de07-4c8f-80b9-b5cb5a1028b4 , @FileName:QQGroup.JPG , @StoredFileName:97257962-a03f-45e1-b6ff-e2c11fb1a514.JPG , @Length:98 , @UploadDate:2016/12/3 21:45:50 , @UploadIPAddress:::1 , 
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Linkup.Data.DatabaseWrapper.ExcuteSqlExpression(SqlExpression sqlExpression) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 310

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:45:56

Title:用户 'sa' 登录失败。

Message: INSERT INTO [File] ([Id],[Domain],[FileName],[StoredFileName],[Length],[UploadDate],[UploadIPAddress]) VALUES(@Id,@Domain,@FileName,@StoredFileName,@Length,@UploadDate,@UploadIPAddress)
@Id:f29bcf78-fa3c-4a7b-94ec-98d252bc32ca , @Domain:2a58d820-de07-4c8f-80b9-b5cb5a1028b4 , @FileName:QQGroup2.jpg , @StoredFileName:0864406e-9779-4ca5-b74e-89f9e99f4306.jpg , @Length:62 , @UploadDate:2016/12/3 21:45:56 , @UploadIPAddress:::1 , 
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Linkup.Data.DatabaseWrapper.ExcuteSqlExpression(SqlExpression sqlExpression) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 310

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:47:00

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:47:01

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:47:01

Title:用户 'sa' 登录失败。

Message: INSERT INTO [File] ([Id],[Domain],[FileName],[StoredFileName],[Length],[UploadDate],[UploadIPAddress]) VALUES(@Id,@Domain,@FileName,@StoredFileName,@Length,@UploadDate,@UploadIPAddress)
@Id:c6424d45-cbb4-410a-b6d6-820ca933185c , @Domain:2a58d820-de07-4c8f-80b9-b5cb5a1028b4 , @FileName:QQGroup2.jpg , @StoredFileName:ba28a1c5-689d-4dbd-be6a-4887655f86b0.jpg , @Length:62 , @UploadDate:2016/12/3 21:47:01 , @UploadIPAddress:::1 , 
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Linkup.Data.DatabaseWrapper.ExcuteSqlExpression(SqlExpression sqlExpression) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 310

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:47:01

Title:用户 'sa' 登录失败。

Message: SELECT * FROM [FileDownloadQueue] WHERE [Status] = @status ORDER BY [CreateTime] ASC
[{"ParameterName":"@status","Value":0}]
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetNewOpenConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetWrappedConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.LoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteDataSet(DbCommand command)
   在 Linkup.Data.DatabaseWrapper.ExecuteDataSet(CommandType commandType, String commandText, List`1 parameterList, String[] tableNameArray) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 264

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:48:20

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:48:21

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:48:22

Title:用户 'sa' 登录失败。

Message: SELECT * FROM [FileDownloadQueue] WHERE [Status] = @status ORDER BY [CreateTime] ASC
[{"ParameterName":"@status","Value":0}]
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetNewOpenConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetWrappedConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.LoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteDataSet(DbCommand command)
   在 Linkup.Data.DatabaseWrapper.ExecuteDataSet(CommandType commandType, String commandText, List`1 parameterList, String[] tableNameArray) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 264

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:48:22

Title:用户 'sa' 登录失败。

Message: INSERT INTO [File] ([Id],[Domain],[FileName],[StoredFileName],[Length],[UploadDate],[UploadIPAddress]) VALUES(@Id,@Domain,@FileName,@StoredFileName,@Length,@UploadDate,@UploadIPAddress)
@Id:c6424d45-cbb4-410a-b6d6-820ca933185c , @Domain:2a58d820-de07-4c8f-80b9-b5cb5a1028b4 , @FileName:QQGroup2.jpg , @StoredFileName:690adbc4-a75e-46b0-a025-7ba99b30f8d6.jpg , @Length:62 , @UploadDate:2016/12/3 21:48:22 , @UploadIPAddress:::1 , 
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Linkup.Data.DatabaseWrapper.ExcuteSqlExpression(SqlExpression sqlExpression) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 310

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:49:37

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:49:38

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:49:38

Title:用户 'sa' 登录失败。

Message: INSERT INTO [File] ([Id],[Domain],[FileName],[StoredFileName],[Length],[UploadDate],[UploadIPAddress]) VALUES(@Id,@Domain,@FileName,@StoredFileName,@Length,@UploadDate,@UploadIPAddress)
@Id:c6424d45-cbb4-410a-b6d6-820ca933185c , @Domain:2a58d820-de07-4c8f-80b9-b5cb5a1028b4 , @FileName:QQGroup2.jpg , @StoredFileName:470ba160-0c1a-4fd3-8519-a01a4f5f58a1.jpg , @Length:62 , @UploadDate:2016/12/3 21:49:38 , @UploadIPAddress:::1 , 
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Linkup.Data.DatabaseWrapper.ExcuteSqlExpression(SqlExpression sqlExpression) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 313

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:49:38

Title:用户 'sa' 登录失败。

Message: SELECT * FROM [FileDownloadQueue] WHERE [Status] = @status ORDER BY [CreateTime] ASC
[{"ParameterName":"@status","Value":0}]
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetNewOpenConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.GetWrappedConnection()
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.LoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteDataSet(DbCommand command)
   在 Linkup.Data.DatabaseWrapper.ExecuteDataSet(CommandType commandType, String commandText, List`1 parameterList, String[] tableNameArray) 位置 d:\WorkFloder\WeixinConstruction\trunk\SourceCode\Common\Linkup.Data\DatabaseWrapper.cs:行号 268

Severity: Error

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:52:09

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/3 21:52:10

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/4 0:14:42

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/4 0:14:42

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/5 0:20:50

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/5 0:20:50

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/7 10:23:10

Title:Application_Start

Message: 

Severity: Information

----------------------------------------
----------------------------------------
Timestamp: 2016/12/7 10:23:11

Title:Redis 连接成功

Message: 

Severity: Information

----------------------------------------
